title: Jon-Paul Boyd
logo: "/images/jpb_portrait.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Blaa Blaa
  <br><br>
  Blaa Blaa
  <br><br>
  <a href="https://www.linkedin.com/in/jonpaulboyd/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
